### ISSUE TITLE
高亮插件对原始编辑器不起作用

### ISSUE THREAD

**Issue by Oberon-Zheng** [bhsd-harry/Wikiplus-highlight#12]
即使勾选了应用于其他编辑器的选项
![image](https://github.com/bhsd-harry/Wikiplus-highlight/assets/18097801/314c634d-0bea-4725-9ae4-6f78050d45b8)

编辑页面里也没有高亮，只有wikiplus自己的编辑器有高亮，从F12看到的结果是
![image](https://github.com/bhsd-harry/Wikiplus-highlight/assets/18097801/b3cc51c0-f74b-4d83-afb8-df42dbad74e1)

在这之前都好好的。

**Comment by bhsd-harry** [comment]
@Oberon-Zheng 是能看到高亮但是所有插件都没生效吗？

**Comment by Oberon-Zheng** [comment]
> @Oberon-Zheng 是能看到高亮但是所有插件都没生效吗？

快速编辑的编辑器下能看到高亮也有这些插件，但是编辑页面那个编辑器并不生效（连高亮都没有）。
之前勾选这个选项这两个编辑器是都能高亮的，而且插件也都起作用

**Comment by bhsd-harry** [comment]
@Oberon-Zheng 没有高亮的话是萌百的问题，已知会萌百各界面管理员。
