### ISSUE TITLE
语法高亮在条目空间似乎失效

### ISSUE THREAD

**Issue by doubanchan** [bhsd-harry/Wikiplus-highlight#14]
不清楚哪边的更动，最近高亮插件在维基条目空间似乎未生效，只在安装该插件的个人主页的js页面起作用。可以开启快速编辑框，只是目前效果类似普通的文本编辑器。
![highlight 2023-09-02 074350](https://github.com/bhsd-harry/Wikiplus-highlight/assets/129359826/84efa33a-7a2b-4339-a6e3-33421e20c058)
这个报告不知道是否有用
![report 2023-09-02 081350](https://github.com/bhsd-harry/Wikiplus-highlight/assets/129359826/0bdf3f09-f6d1-4557-900f-75243a611394)

**Comment by bhsd-harry** [comment]
已于 5669dd3454ae121ddbd22bc2fba49a6d200ad1ea 修复，我晚点找时间发一下包。
