### ISSUE TITLE
[BUG]在Safari上不会显示光标

### ISSUE THREAD

**Issue by GarliC-C** [bhsd-harry/Wikiplus-highlight#4]
在Safari上使用该插件后，不会显示输入光标的位置，但是可以正常输入。

Safari 版本15.4 Mac (17613.1.17.1.13)

**Comment by bhsd-harry** [comment]
@GarliC-C 请问是在哪个网站使用什么皮肤？

**Comment by GarliC-C** [comment]
r6s.huijiwiki.com

只是按照最基本的方法引入，没有特别做其他设置。

ps：在站点中点击右上角⚙️图标-参数设置-小工具，可以启动Wikiplus和Highlight插件。

Highlight插件的代码位于站点页面[[Gadget:WikiplusHighlight.js]]下,只有一行mw库的load方法。

不确定是否和Wikiplus有关，但是Wikiplus确实有做一些比较小的修改（在加载完成后移动按钮的位置到左边侧栏）它位于[[Gadget:Wikiplus.js]]

**Comment by GarliC-C** [comment]
个人认为是Safari的兼容性存在问题。

因为在Wikipedia也是这样的情况。我在Wikipedia使用的皮肤是Timeless。

**Comment by bhsd-harry** [comment]
@GarliC-C 我没找出直接原因，特别是我发现这个问题在LLWiki上就不存在，但在中文维基百科和萌娘百科我也能复现。现在在2.6.1版本中已临时修复，stable版本因为CDN的缓存可能会晚一周左右。

**Comment by GarliC-C** [comment]
问题已经得到修复👍

**Comment by bhsd-harry** [comment]
@GarliC-C 因为更换jsdelivr域名不是一个正规解，我就不添加进README.md了。不过这里回复一下大佬，表示r6s维基上的留言是我留的。

**Comment by GarliC-C** [comment]
> @GarliC-C 因为更换jsdelivr域名不是一个正规解，我就不添加进README.md了。不过这里回复一下大佬，表示r6s维基上的留言是我留的。

感谢帮助，顺便分享一个有趣的事情：
昨天我的梯子过期了，然后提供方没有自动续费，他们的用户中心的登录界面按下登陆后没反应，看了一下控制台显示来自于`https://cdn.jsdelivr.net/npm/perfops-rom`的外部调用没有加载成功导致的。真是被头疼到了。

**Comment by bhsd-harry** [comment]
> 感谢帮助，顺便分享一个有趣的事情： 昨天我的梯子过期了，然后提供方没有自动续费，他们的用户中心的登录界面按下登陆后没反应，看了一下控制台显示来自于`https://cdn.jsdelivr.net/npm/perfops-rom`的外部调用没有加载成功导致的。真是被头疼到了。

哈哈！主要是jsdelivr作为一款功能强大的免费CDN太流行了吧，没想到现在不得不撤出中国。
