### ISSUE TITLE
[BUG]模板名称中含有空格时右键跳转不正确

### ISSUE THREAD

**Issue by GuoPCinGitHub** [bhsd-harry/Wikiplus-highlight#5]
如题，如{{用户 Comic Girls}}在点击“用户”“Comic”“Girls”会分别跳转至[[模板:用户]]、[[模板:Comic]]以及[[模板:Girls]]。

**Comment by bhsd-harry** [comment]
@GuoPCinGitHub 感谢大佬反馈！已于2.14.1版本中修复。
