### ISSUE TITLE
[BUG]手机无法正常选择文字

### ISSUE THREAD

**Issue by Qwerty-up** [bhsd-harry/Wikiplus-highlight#7]
我发现了Wikiplus高亮插件的一个bug。在我试图在手机使用Wikiplus语法高亮插件编辑页面时，不管我位于手机端还是电脑端网页，我都无法在选择文字时自由设定选择范围，最多只能选择一个汉字或者拉丁字母单词。而且在选择文字时，我的浏览器也不会弹出剪切·复制的文字框。因为我在编辑维基百科时经常使用这些功能，这对我的编辑造成了很大的困扰。我使用OPPO手机自带浏览器/Chrome浏览器。谢谢！

**Comment by bhsd-harry** [comment]
@Qwerty-up 手机无法正常使用是上游CodeMirror的问题，本高亮工具不支持手机使用。

**Comment by bhsd-harry** [comment]
@Qwerty-up 根据[Phabricator上的讨论](https://phabricator.wikimedia.org/T285660)，尝试关闭了Android手机上的行号显示。但我没有Android设备可供测试，请协助检查[最新版本](https://unpkg.com/wikiplus-highlight/dist/main.min.js)能否选中并剪切/复制。

**Comment by Qwerty-up** [comment]
去重新测试了一遍，应该是搜索插件的问题，只要关闭搜索插件就可以正常选择文字了。

**Comment by bhsd-harry** [comment]
> 去重新测试了一遍，应该是搜索插件的问题，只要关闭搜索插件就可以正常选择文字了。

@Qwerty-up 这就很奇怪了……是只有自带浏览器这样，还是Chrome也这样？另外你的Chrome版本是多少？

**Comment by Qwerty-up** [comment]
> > 去重新测试了一遍，应该是搜索插件的问题，只要关闭搜索插件就可以正常选择文字了。
> 
> @Qwerty-up 这就很奇怪了……是只有自带浏览器这样，还是Chrome也这样？另外你的Chrome版本是多少？

自带浏览器和Chrome浏览器都有这个现象。我的Chrome版本是Chrome 78.0.3904.96。

**Comment by bhsd-harry** [comment]
@Qwerty-up 我找了几位大佬帮忙测试，看上去应该和手机安装的键盘有关，和浏览器关系不大。这样的话恕无法修复。

**Comment by Qwerty-up** [comment]
谢谢。
